name: oneroom_finder
description: "A new Flutter project."

publish_to: 'none' # 비공개 패키지로 설정

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0" # Flutter SDK 버전 설정

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  shared_preferences: ^2.3.3
  firebase_auth: ^5.3.3
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  webview_flutter: ^4.0.0
  intl: ^0.18.0
  provider: ^6.1.2
  flutter_inappwebview: ^6.1.5
  flutter_naver_map: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true  # Material Design 아이콘 사용 설정
  assets:
    - assets/logo.png
    - assets/map.png
